import os

def build_markdown_report(records):
    """
    Membuat konten tabel markdown dari list of records.
    """
    if not records:
        return "# Rekap Nilai Mahasiswa\n\nTidak ada data mahasiswa."

    # Header Tabel
    header = "| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |"

    # Separator: Alignment sesuai contoh output (Hadir: kanan, Nilai Akhir: kanan, Predikat: tengah)
    # Catatan: Markdown hanya mendukung kiri/kanan/tengah, jadi kita buat Nilai Akhir kanan (---|:) dan Predikat tengah (---:/:---)
    # Berdasarkan contoh output tugas: Nilai Akhir menggunakan 'kanan' dan Predikat menggunakan 'tengah' atau 'kanan' (kita pakai tengah untuk predikat)
    # Contoh output: |---|---|---|:|::| (yang berarti: Kiri, Kiri, Kiri, Kanan, Kanan/Tengah)
    separator = "|---|---|---:|:---:|:---:|" 

    content = "# Rekap Nilai Mahasiswa\n"
    content += header + "\n"
    content += separator + "\n"

    # Baris Data
    for rec in records:
        baris = (
            f"| {rec['nim']} "
            f"| {rec['nama']} "
            f"| {rec['hadir_persen']:.1f} " # Hadir (%) dengan 1 desimal
            f"| {rec['nilai_akhir']:.2f} " # Nilai Akhir dengan 2 desimal
            f"| {rec['predikat']} |"
        )
        content += baris + "\n"

    content += "\nGenerated by student_performance_tracker"
    return content

def save_text(path, content):
    """
    Menyimpan konten teks ke file tertentu (misal: out/report.md).
    """
    try:
        # Pastikan folder output ada
        os.makedirs(os.path.dirname(path), exist_ok=True) 

        with open(path, 'w') as f:
            f.write(content)
        print(f"\n[SUKSES] Laporan disimpan ke: {path}")
        return True
    except Exception as e:
        print(f"\n[ERROR] Gagal menyimpan file: {e}")
        return False